name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: write
  contents: read

jobs:
  test-github:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.10']
        julia-arch: [x64]
        os: [ubuntu-latest,macos-latest,windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }} 
      - uses: julia-actions/cache@v1
      - run: julia --color=yes --project=.ci .ci/ci.jl
